services:
  # Banco de Dados
  mongodb:
    image: mongo:latest
    container_name: gdash_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongo_data:/data/db
    networks:
      - gdash_net

  # Fila
  rabbitmq:
    image: rabbitmq:3-management
    container_name: gdash_rabbitmq
    ports:
      - "5672:5672"   # Porta para comunicação (Python/Go)
      - "15672:15672" # Porta do painel de gestão (Browser)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - gdash_net

volumes:
  mongo_data:
  rabbitmq_data:

networks:
  gdash_net:
    driver: bridge